# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: cloudflare-ddns
version: 2
builds:
  - binary: cloudflare-ddns
    goos:
      - "windows"
      - "darwin"
      - "linux"
      - "freebsd"
      - "openbsd"
      - "solaris"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "7"
    ignore:
      - goos: "darwin"
        goarch: "386"
      - goos: "openbsd"
        goarch: "arm"

brews:
  - repository:
      owner: wyattjoh
      name: homebrew-stable
    directory: Formula
    homepage: https://github.com/wyattjoh/cloudflare-ddns
    description: Cloudflare Dynamic DNS Updater
    test: |
      system "#{bin}/cloudflare-ddns -v"
    install: |
      bin.install "cloudflare-ddns"

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE.md
      - README.md

release:
  github:
    owner: wyattjoh
    name: cloudflare-ddns
